mobarena-addon:
  enable: false
  whitelist:
    - PLAYER
    - WOLF
    - OCELOT
    - IRON_GOLEM
    - HORSE
safe-portal:
  enable: false
  messages:
    cancelled: Sorry, but the teleportation has been cancelled due to the destination is out of border.
global:
  messages:
    reloaded: MoeUtils has been reloaded.