# Configuration of MoeUtils

lang: zh_cn
magictime:
  cost: 50
  cooldown: 600
magicweather:
  cost: 50
  cooldown: 600
betterbees:
  enable: true
  requireSneak: false
betterportals:
  enable: true
  debug: true
deathlogger:
  enable: true
  # The radius of searching for nearby players around the death entity.
  # The search only happens if there is no direct killer to the death entity.
  searchRadius: 16
  # List of creatures that should be logged when died.
  creatures:
  - villager
foundores:
  enable: true
  # Max search attempts. Higher values may cause more lag.
  maxIterations: 32
  # The interval (in second) between this plugin resets location history.
  purgeInterval: 1800
  # List of worlds where you want to enable announcement.
  worlds:
  - world
  - world_the_end
  - world_nether
  # List of blocks which need to be announced.
  blocks:
  - coal_ore
  - nether_quartz_ore
  - iron_ore
  - diamond_ore
  - gold_ore
  - emerald_ore
  - lapis_ore
  - redstone_ore
mobarena:
  enable: true
  # List of creatures that DO NOT collide with the arrows from players.
  whitelist:
  - ocelot
  - iron_golem
  - player
  - wolf
  - horse
